name: GitHub Stats Card
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to run this manually

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Top Langs Card
        uses: stats-organization/github-readme-stats-action@v1
        with:
          card: top-langs
          # include_all_commits=true is the key to finding your work from the last 2 years
          options: username=rafi983&theme=vision-friendly-dark&show_icons=true&include_all_commits=true&count_private=true&hide=css,html,scss,less,shell&layout=compact&langs_count=10
          path: ./top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add top-langs.svg
          git commit -m "Update GitHub Language Stats" || exit 0
          git push
