
<!--START_SECTION:waka-->



name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.5b9c8658-ea5e-493a-ad79-98d3b13ec33e }}
          GH_TOKEN: ${{ secrets.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 }}


- name: Profile Readme Development Stats
  uses: anmol098/waka-readme-stats@V3

<!--END_SECTION:waka-->





