name: GitHub-Profile-3D-Contrib

on:
  # 03:00 JST == 18:00 UTC
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push (if changes)
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if [ $(git status --porcelain | wc -l) -ne 0 ]; then
            git commit -m "Updated GitHub profile 3D contribution"
            git push
          else
            echo "No changes detected. Skipping commit."
          fi
