name: GitHub-Profile-3D-Contribution

on:
  schedule:
    - cron: "0 */18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
    - uses: actions/checkout@v2
    - uses: yoshi389111/github-profile-3d-contrib@0.7.1  # Update version
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        USERNAME: ${{ github.repository_owner }}  # Use retrieved username
        # Commented out for now (uncomment if needed)
        # MAX_REPOS: ${{ github.repository_count }} 
    # Existing step(s) for generating the image (replace with ...)
    - git commit -m "3D Contribution image updated for user: ${rafi983}"  # Informational commit message
    - name: Check repository count (optional)  # Update with actual commands
      run: |
        if [[ ${MAX_REPOS} -lt 10 ]]; then
          # Replace this comment with your actual image generation commands
          # (e.g., generate image, add to git, commit)
        fi
    - git push  # Existing push step


